userName=Admin

password=admin123

pageURL=https://www.facebook.com/

warningMessage=Please Check the Browser Configuration

browserName=edge

screenshotPath=.//src//test//resources//Screenshots

reportPath=.//src//test//resources//Reports